# Generated by Django 4.1.1 on 2022-09-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=20)),
                ('edoj', models.DateField()),
                ('edsig', models.CharField(max_length=20)),
                ('eexp', models.FloatField()),
                ('ecompany', models.CharField(max_length=20)),
                ('eesal', models.IntegerField()),
            ],
        ),
    ]
